apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-processing-app
  namespace: ai-process
  labels:
    app: eks-ai-processing-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-ai-processing-app
  template:
    metadata:
      labels:
        app: eks-ai-processing-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - name: ai-image-processer
        image: / ECR IMAGE ****
        ports:
        - name: http
          containerPort: 5000
        imagePullPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux