apiVersion: v1
kind: Service
metadata:
  name: ai-lb-service
  namespace: ai-process
spec:
  type: LoadBalancer
  selector:
    app: eks-ai-processing-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000